DROP TABLE IF EXISTS elo_group;

CREATE TABLE elo_group (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name CHAR(32) UNIQUE NOT NULL,
	description TEXT NOT NULL
);

/*

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        username TEXT UNIQUE NOT NULL,  
        password TEXT NOT NULL
);

CREATE TABLE post (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        author_id INTEGER NOT NULL,
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        FOREIGN KEY (author_id) REFERENCES user (id)
);

*/
